// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqYLw8ohsIyGEDrcdbV4hxpUD5P1amZro',
    appId: '1:489513304456:web:49a47aff2d26fc6075fa3d',
    messagingSenderId: '489513304456',
    projectId: 'wildguardproject',
    authDomain: 'wildguardproject.firebaseapp.com',
    storageBucket: 'wildguardproject.firebasestorage.app',
    measurementId: 'G-LQN9YFR7WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEqU4meTWIosy6RngIykH4UZPB_a7nqT0',
    appId: '1:489513304456:android:62906224817294c375fa3d',
    messagingSenderId: '489513304456',
    projectId: 'wildguardproject',
    storageBucket: 'wildguardproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY_XNxCPdzSGeWzdMf_s6dJigXL6r8B7s',
    appId: '1:489513304456:ios:e756934be685824575fa3d',
    messagingSenderId: '489513304456',
    projectId: 'wildguardproject',
    storageBucket: 'wildguardproject.firebasestorage.app',
    iosBundleId: 'com.example.wildguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY_XNxCPdzSGeWzdMf_s6dJigXL6r8B7s',
    appId: '1:489513304456:ios:e756934be685824575fa3d',
    messagingSenderId: '489513304456',
    projectId: 'wildguardproject',
    storageBucket: 'wildguardproject.firebasestorage.app',
    iosBundleId: 'com.example.wildguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqYLw8ohsIyGEDrcdbV4hxpUD5P1amZro',
    appId: '1:489513304456:web:42d32cc54b07047c75fa3d',
    messagingSenderId: '489513304456',
    projectId: 'wildguardproject',
    authDomain: 'wildguardproject.firebaseapp.com',
    storageBucket: 'wildguardproject.firebasestorage.app',
    measurementId: 'G-CZQSPDCWRR',
  );
}
